version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 2
    rebase-strategy: disabled
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 2
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
    ignore:
      # Major version must correspond with the used Node.js version.
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major
    groups:
      all-direct:
        patterns:
          - "*"
        update-types:
          - patch
      mdx:
        patterns:
          - "@mdx-js/*"
        update-types:
          - major
          - minor
      nextjs:
        patterns:
          - "@next/*"
          - eslint-config-next
          - next
        update-types:
          - major
          - minor
      react:
        patterns:
          - "@types/react"
          - "@types/react-dom"
          - react
          - react-dom
        update-types:
          - major
          - minor
      tailwindcss:
        patterns:
          - "@tailwindcss/*"
          - tailwindcss
        update-types:
          - major
          - minor
    rebase-strategy: disabled
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 2
    allow:
      - dependency-type: indirect
    groups:
      all-indirect:
        patterns:
          - "*"
    rebase-strategy: disabled
    # Makes it possible to have another config. for the same dir.
    # https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
    target-branch: main
