version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 2
    rebase-strategy: disabled
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 2
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
      # Major version must correspond with the used Node.js version.
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major
          - version-update:semver-patch
    groups:
      mdx:
        patterns:
          - "@mdx-js/*"
      nextjs:
        patterns:
          - "@next/*"
          - eslint-config-next
          - next
      react:
        patterns:
          - "@types/react"
          - "@types/react-dom"
          - react
          - react-dom
      tailwindcss:
        patterns:
          - "@tailwindcss/*"
          - tailwindcss
    rebase-strategy: disabled
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 2
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    groups:
      all-packages:
        patterns:
          - "*"
    rebase-strategy: disabled
    # Makes it possible to have another config. for the same dir.
    # https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
    target-branch: main
